url: https://johnmckinght.github.io
baseurl: /portofolio/

# Site settings
title: Erudite Training Provider
email: your-email@domain.com
description: "Erudite adalah Provider Kursus Digital Marketing"
intro_leading: "Selamat Datang!"
intro_heading: "Senang Berjumpa dengan Anda"

# Services
# services:
#   - title: "Google Adwords"
#     heading: "Running a campaign without knowing how to use the platform can be a recipe for burning money fast"
#   - title: "Google Analytics"
#     heading: "Mengerti pengunjung website anda dan apa yang mereka inginkan adalah faktor sukses penting untuk digital marketing"
#   - title: "B2B Marketing"
#     heading: "Business-to-business marketing (atau B2B marketing) adalah penjualan produk atau jasa dari satu perusahaan kepada perusahaan yang lain"
#   - title: "Digital Marketing"
#     heading: "Cara orang berinteraksi dengan bisnis telah berubah secara dramatis selama beberapa tahun terakhir dengan munculnya media online"
#   - title: "Market Place"
#     heading: "Ibarat bermain bola, semua orang bisa menendang bola. Namun kalau tidak bisa bermain cantik, maka pemain tersebut dapat keluar sebagai pemenang"
#   - title: "Tips & Tricks"
#     heading: "Berbagi tips dalam dunia marketing"

collections:
  services:

# Team names, titles and social links
people:
- name: Agus Laifa
  pic: agus-laifa-262x300
  position: Lead Designer
  description: Agus Laifa, S. Kom. seorang praktisi digital marketing yang telah berpengalaman sejak tahun 2005. Setelah lulus kuliah jurusan sistem informasi, Agus Laifa berkarya di percetakan, konsultan manajemen, digital marketing dan perusahaan eCommerce. Menangani proyek digital marketing untuk beberapa klien nasional maupun internasional dari berbagai latar belakang industri memberikan pengalaman yang signifikan untuk marketing and sales growth hacking. Saat ini, Agus Laifa menjadi salah satu konsultan digital marketing paling berpengaruh di Indonesia dan mempunyai passion untuk memberikan pemahaman yang benar mengenai implementasi digital marketing marketing kepada seluruh pemilik brand dan bisnis atau Digital Literate. Motto Agus Laifa adalah "Running a campaign without knowing how to use the platform can be a recipe for burning money fast." Agus Laifa telah mendapatkan sertifikasi resmi untuk bidang Google Adwords, Google Analytics, Digital Sales, Mobile Sites, Video Ads dan Online Professional.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty